apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-beta
  namespace: default
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure        
          containers:
          - name: busybox
            image: busybox
            imagePullPolicy: Always