apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app2-production-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: busybox