apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

configMapGenerator:
- name: cronjob-template-cron-env
  namespace: default
  envs: [cronjob-template.env]
  behavior: merge
  options:
    disableNameSuffixHash: true

patchesStrategicMerge:
  - cronjob-template.yaml

patches:
- target:
    kind: CronJob
  patch: |-
    - op: replace
      path: /metadata/name
      value: cronjob-template
    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/0/name
      value: cronjob-template