apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: base
  namespace: default
spec:
  schedule: "*/45 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: base
            image: gcr.io/hu-cloud-189316/busybox
            envFrom:
            - configMapRef:
                name: cronjobB-env