apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-alpha
  namespace: default
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure         
          containers:
          - name: busybox
            image: busybox
            imagePullPolicy: Always