apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app1-production-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: busybox