apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

configMapGenerator:
- name: cronjob-alpha-cron-env
  namespace: default
  envs: [cronjob-alpha.env]
  behavior: create
  options:
    disableNameSuffixHash: true

patchesStrategicMerge:
  - cronjob-alpha.yaml

patches:
- target:
    kind: CronJob
  patch: |-
    - op: replace
      path: /metadata/name
      value: cronjob-alpha
    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/0/name
      value: cronjob-alpha